# Generated by Django 2.1.3 on 2018-11-11 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('editora', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foto', models.ImageField(upload_to='')),
                ('categoria', models.CharField(choices=[('LI', 'Literatura'), ('TI', 'Tecnologia da Informação'), ('FI', 'Filosofia'), ('HI', 'História'), ('EL', 'Eletrônica'), ('PT', 'Português'), ('DI', 'Direito'), ('AD', 'Administração'), ('MT', 'Matemática'), ('ED', 'Educação'), ('IB', 'Informática Básica'), ('NC', 'Não Classificado'), ('CO', 'Comunicação'), ('AR', 'Arte'), ('PO', 'Política'), ('ME', 'Medicina'), ('CN', 'Contabilidade'), ('MO', 'Metodologia'), ('MK', 'Marketing'), ('PN', 'Planejamento'), ('BI', 'Biologia'), ('FI', 'Física'), ('NE', 'Negociação'), ('PS', 'Psicologia'), ('QI', 'Química')], default='NC', max_length=2)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
